### ISSUE TITLE
error Failed at the npmmirror-config-china@1.0.2 install script

### ISSUE THREAD

**Issue by dmanbu** [neekin/npmmirror-config-china#2]
使用如下命令安装：
```
npm install --unsafe-perm -g npmmirror-config-china --registry=https://registry.npmmirror.com --bin-mirrors-prefix=https://npmmirror.com/mirrors
```

错误信息如下：
```
669 verbose lifecycle npmmirror-config-china@1.0.2~install: unsafe-perm in lifecycle true
670 verbose lifecycle npmmirror-config-china@1.0.2~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/npmmirror-config-china/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/go/bin:/root/bin
671 verbose lifecycle npmmirror-config-china@1.0.2~install: CWD: /usr/lib/node_modules/npmmirror-config-china
672 silly lifecycle npmmirror-config-china@1.0.2~install: Args: [ '-c', 'node lib/install.js' ]
673 silly lifecycle npmmirror-config-china@1.0.2~install: Returned: code: 1  signal: null
674 info lifecycle npmmirror-config-china@1.0.2~install: Failed to exec install script
675 timing action:install Completed in 1318ms
676 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
677 timing stage:rollbackFailedOptional Completed in 34ms
678 timing stage:runTopLevelLifecycles Completed in 2004ms
679 verbose stack Error: npmmirror-config-china@1.0.2 install: `node lib/install.js`
679 verbose stack Exit status 1
679 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
679 verbose stack     at EventEmitter.emit (events.js:189:13)
679 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
679 verbose stack     at ChildProcess.emit (events.js:189:13)
679 verbose stack     at maybeClose (internal/child_process.js:970:16)
679 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
680 verbose pkgid npmmirror-config-china@1.0.2
681 verbose cwd /root
682 verbose Linux 3.10.0-1160.el7.x86_64
683 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "npmmirror-config-china" "--registry=https://registry.npmmirror.com" "--bin-mirrors-prefix=https://npmmirror.com/mirrors"
684 verbose node v10.15.3
685 verbose npm  v6.4.1
686 error code ELIFECYCLE
687 error errno 1
688 error npmmirror-config-china@1.0.2 install: `node lib/install.js`
688 error Exit status 1
689 error Failed at the npmmirror-config-china@1.0.2 install script.
689 error This is probably not a problem with npm. There is likely additional logging output above.
690 verbose exit [ 1, true ]
```

**Comment by javaswing** [comment]
@dmanbu 我安装也出错了，先用这个吧
```shell
npm config set registry https://registry.npmmirror.com \
 && npm install --unsafe-perm -g mirror-config-china
```
